### PR TITLE
Wait Less

### PR DESCRIPTION
**Pull request by lalexgap**
Lowers the max wait to 20 seconds and also scales it less aggressively with concurrent payments

### CODE REVIEW

**Comment by geoknee** [comment]
Can you remind what the point of the wait / sleep is?

**Comment by NiloCK** [comment]
One of the sleeps is to allow enough time for ledger channels to be established before starting the clock on TTFP for virtualfund operations - see https://github.com/statechannels/go-nitro-testground/pull/138.

I'm not certain about the other usage.

**Comment by lalexgap** [comment]
> One of the sleeps is to allow enough time for ledger channels to be established before starting the clock on TTFP for virtualfund operations - see #138.
> 
> I'm not certain about the other usage.

The other usage is to allow all the virtual channels to close before we attempt to close the ledger channels. If we close the ledger channels too quick we run into https://github.com/statechannels/go-nitro/issues/744

**Comment by geoknee** [comment]
Longer term solution might be to have all instances wait for all direct fund objectives to complete?

**Review by geoknee — APPROVED** [review]

**Pull request merged**
